# Command line tools
brew "bat"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "lsd"
brew "neovim"
brew "openssh"
brew "ripgrep"
brew "starship"

# Development programs
brew "actionlint"
tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"
cask "iterm2"
cask "visual-studio-code"

# General programs
cask "1password"
cask "bettertouchtool"
cask "discord"
