# Command line tools
brew "fd"
brew "git"
brew "lsd"
brew "neovim"
brew "openssh"
brew "ripgrep"

# Development programs
tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"
cask "visual-studio-code"

# General programs
cask "1password"
cask "discord"
tap "nextfire/tap"
brew "nextfire/tap/apple-music-discord-rpc", restart_service: :changed
